syntax = "proto3";

option csharp_namespace = "tmr_shared.Protos";

package auth;

service AuthService {
  rpc Login (LoginRequest) returns (AuthResponse);
}

message LoginRequest {
  string user = 1;
  string password = 2;
}

message AuthResponse {
  string accessToken = 1;
  string refreshToken = 2;
  string expiresAt = 3;
  string tokenFamilyId = 4;
  UserResponse user = 5;
}

message UserResponse {
  int32 id = 1;
  string email = 2;
  string name = 3;
  string createdAt = 4;
  int32 idEmpleado = 5;
}
